# Site Settings

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]

# Tret del tio de youtube que ho fa sense template
exclude: ['README.md']
baseurl: /cat


